trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: InstallDependencies
    displayName: "Install Dependencies"
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: "Install Python Requirements"

- stage: Deploy
  jobs:
  - deployment: DeployToAzure
    displayName: "Deploy to Azure"
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              # Setup Gunicorn to serve the app
              gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
            displayName: "Run Gunicorn"
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '<Azure Subscription>'
              appName: '<Your App Service Name>'
              package: '$(Pipeline.Workspace)/drop'
